apiVersion: v1
kind: ConfigMap
metadata:
  name: collector-configmap
data:
  otel.yaml: |
    extensions:
      health_check:
    
    receivers:
      otlp:
        protocols:
          grpc:
    
    processors:
      batch:
    
    exporters:
      logging/logging_debug:
        loglevel: debug
      logging/logging_info:
        loglevel: info
    
    service:
      pipelines:
        traces:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ logging/logging_info ]
        metrics:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ logging/logging_info ]
        logs:
          receivers: [ otlp ]
          processors: [ batch ]
          exporters: [ logging/logging_info  ]
    
      extensions: [ health_check ]
    
